#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Client.Android.Resource", IsApplication=true)]

namespace Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int colorAccent = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int colorPrimary = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_margin = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int button_height = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int status_text_bottom_padding = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int status_text_size = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int connectButton = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int endButton = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int ipText = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int nextButton = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int portText = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int prevButton = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int statusText = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Remote = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int End = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int InvalidInput = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int Next = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int NoConnection = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int Prev = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int YesConnection = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int connectButton = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int ipHint = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int portHint = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
